### ISSUE TITLE
Pilot WP

### ISSUE THREAD

**Issue by aprof28** [mtr81/kodi_addons#10]
Witam. Potrzebna pomoc. Na programie Puls 2  w dolnym prawym rogu wyskakuje " Wyłączenie odtwarzacza za 3 minuty " .Jak to wyłączyć ?  Bo co 3 minuty trzeba program włączyć.  Z góry dziękuje.

**Comment by mtr81** [comment]
Ze strony użytkownika nie ma takiej możliwości. Jako jedyny z paczki bezpłatnych kanałów jest objęty DRM co wymusza użycie manifestu MPD. Z kolei tego typu manifesty w tym serwisie są dodatkowo zabezpieczone tak, że tracą ważność za 3 minuty od rozpoczęcia odtwarzania. I nie chodzi tu o zmianę tokena, co byłoby do ugryzienia. Na tą chwilę nie jestem w stanie znaleźć rozwiązania. Jeżeli chodzi o stacje Pulsu, to są dostępne w jakości HD we wtyczce Megogo bez konieczności logowania.

**Comment by aprof28** [comment]
No nic trudno. To zamykamy temat. Miłej nocy.

**Comment by mtr81** [comment]
> Witam. Potrzebna pomoc. Na programie Puls 2 w dolnym prawym rogu wyskakuje " Wyłączenie odtwarzacza za 3 minuty " .Jak to wyłączyć ? Bo co 3 minuty trzeba program włączyć. Z góry dziękuje.

Przy okazji innych zmian udało się temat ogarnąć. W wersji 1.0.5 wtyczki powinno odtwarzać przedmiotowy kanał bez ograniczeń czasowych.

**Comment by aprof28** [comment]
Bardzo dziękuję. Korzystałem z Megogo i CDA. Zdrowia życzę.

**Comment by mtr81** [comment]
Dzięki! Wzajemnie ;-)
