### ISSUE TITLE
TVP_VOD

### ISSUE THREAD

**Issue by aprof28** [mtr81/kodi_addons#11]
Witam. Czy mógłbyś programy regionalne z Na żywo(TV) przełożyć do TVP GO telewizja, Kanały na żywo przełożyć.  Jeżeli można ? Bo tam nie działają z powodu ip. Jestem w DE.

**Comment by mtr81** [comment]
Witam
Kanały w sekcjach Telewizja/Kanały na żywo oraz Na żywo (TV) pochodzą z dwóch różnych źródeł i ich wymieszanie nie jest dobrym pomysłem. Do oglądania TV korzystasz bezpośrednio z wtyczki, czy przy użyciu IPTV Simple Client? Jak z tej drugiej opcji, to mogę dodać do wtyczki generowanie listy dla kanałów z sekcji 'Na żywo (TV)'.

**Comment by aprof28** [comment]
Korzystam z IPTV Siemple Client.

**Comment by mtr81** [comment]
Dodałem w najnowszej wersji możliwość wygenerowania listy kanałów z zakładki "Na żywo (TV)".

**Comment by aprof28** [comment]
Dzięki👍🏻
