### ISSUE TITLE
VOD.pl

### ISSUE THREAD

**Issue by aprof28** [mtr81/kodi_addons#12]
Witam. Mam małą prośbę. Czy mogę prosić o kreatora listy m3u do dodatku VOD.pl . Z góry dziękuję.

**Comment by mayones2** [comment]
Przyłączam się do prośby o generator m3u

**Comment by mtr81** [comment]
Witam
Wrzuciłem do repo wersję wtyczki z generowaniem listy M3U kanałów TV.

**Comment by aprof28** [comment]
Swoją drogą też tak chcę umieć😉🤫. Dzięki  i miłego wieczoru.

**Comment by mayones2** [comment]
Dziękujemy!!!
