### ISSUE TITLE
Toya GO

### ISSUE THREAD

**Issue by Lukasz1234514** [mtr81/kodi_addons#13]
Wtyczka Toya Go nie wyświetla wszystkich kanałów możliwych do obejrzenia.

**Comment by mtr81** [comment]
Dzięki za info.. Możesz podać przykłady, których kanałów nie ma na liście? W chwili obecnej z listy wycinane są programy, które mają etykietę "program niedostępny w twoim pakiecie" oraz "program niedostępny w bieżącej lokalizacji". Wtyczka bazuje na wersji przeglądarkowej serwisu.

**Comment by mtr81** [comment]
OK. Już chyba wiem o co chodzi. Wyciąłem niepotrzebnie kanały niedostępne na zewnątrz nawet w lokalizacjach, gdzie można je oglądać. Dodałem do repo ver. 1.0.4, która powinna rozwiązać problem.

**Comment by Lukasz1234514** [comment]
Nadal nie działa.--Sent from my Android phone with GMX Mail. Please excuse my brevity.On 21.12.2023, 17:39 mtr81 ***@***.***> wrote:

   
  OK. Już chyba wiem o co chodzi. Wyciąłem niepotrzebnie kanały niedostępne na zewnątrz nawet w lokalizacjach, gdzie można je oglądać. Dodałem do repo ver. 1.0.4, która powinna rozwiązać problem.

**Comment by mtr81** [comment]
Nie miało prawa działać, bo do repo poszła stara wersja ;-) Daj znać jak to wygląda z ver. 1.5. Jakby nie działało to napisz jakich kanałów brakuje.

**Comment by Lukasz1234514** [comment]
Wersja 1.05 w ogóle nie działa.

**Comment by mtr81** [comment]
No to do trzech razy sztuka - 1.0.6 poszła do repo.

**Comment by Lukasz1234514** [comment]
teraz działa jednak zaobserwowałem dziwną rzecz, mianowicie po kilku
sekundach włacza się przyśpieszone odtwarzanie fast forrward np x2 lub
x4 ale sprawdzę to jeszcze na innym urządzeniu.

**Comment by Lukasz1234514** [comment]
Wszystko działa już prawidłowo, problem był po mojej stronie.

**Comment by Lukasz1234514** [comment]
Wszystko już działa prawidłowo :)
