### ISSUE TITLE
Polsat News

### ISSUE THREAD

**Issue by mm1992** [mtr81/kodi_addons#14]
Dziś nagle przestał działać Polsat News z wtyczki Polsat News&Sport.
Kiedy wyciągnąłem z kogów Kodi adres manifestu MPD i wysłałem go curl'em, zwraca mi odpowiedź HTTP 403.

**Comment by mtr81** [comment]
Manifest MPD bez problemu pobiera.
```INFO <general>: AddOnLog: inputstream.adaptive: Successfully parsed manifest file. #Periods: 1, #Streams in first period: 4, Type: live, Download speed: 12699494.7386 Bytes/s```
Ale już segmentów nie:
```DEBUG <general>: Curl::Debug - HEADER_IN: HTTP/1.1 404 Not Found```
Onacza to, że strumień został wyłączony.
