### ISSUE TITLE
Player

### ISSUE THREAD

**Issue by Romik2505** [mtr81/kodi_addons#19]
Kodi Omega Player plugin has playback issues with ads. Plays for 2 minutes and stops. This problem does not exist in Kodi Nexus. It works fine there. Can anything be done about it?

**Comment by mtr81** [comment]
I need more details... Pls. attache full log.

**Comment by mtr81** [comment]
I checked live TV and VOD content playback on Kodi 21 (Build: 22-ALPHA1 21.90.700 Compiled: 2024-03-27, ISA ver: 21.4.3, system:  WIN 10) and I didn't see any problems.

**Comment by zuzia-dev** [comment]
@mtr81, pod Linuksem w najświeższej kompilacji, też też jest OK.

**Comment by Romik2505** [comment]
log attached. Plays for up to 2 minutes and stops.
[kodi.log](https://github.com/mtr81/kodi_addons/files/14802958/kodi.log)

**Comment by Romik2505** [comment]
I'm sorry but I attached the wrong log. I'm already correcting it
[kodi.log](https://github.com/mtr81/kodi_addons/files/14803035/kodi.log)

**Comment by mtr81** [comment]
In last log playback started on 11:53:25. Last record in log is dated on 11:54:03. So it's not 2 minutes. Another thing is I need full debug-log...
Except this check kodi player settings - "Allow hardware acceleration DXVA2" must be OFF. 
Do you se VPN?

**Comment by Romik2505** [comment]
The IS update just came out and now it has started working.

**Comment by mtr81** [comment]
Not exactly. Now started from begin of 2-hours timeshift period...

**Comment by Romik2505** [comment]
That is, not much has changed maybe you need to switch to Nexus, there it works well. And wait for some working IS fix. Thanks for the info

**Comment by Romik2505** [comment]
I don't know what you did in ISA, but it probably works well and doesn't stop (pauses), it works continuously. Thanks a lot.

**Comment by mtr81** [comment]
It's not my version. I downloaded it from one of PRs on ISA GH (25th Feb). But it is not solution, because one addon works but other doesn't...

**Comment by Romik2505** [comment]
About. Do you have this version of ISA. on Android too?

**Comment by mtr81** [comment]
No I haven't.

**Comment by Romik2505** [comment]
I was able to find a working z version on PK W ISA GH. dated March 19

**Comment by mtr81** [comment]
Try new version ISA from PR 1518 -> https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1518/7/artifacts/ It solves problem...

**Comment by mtr81** [comment]
The new ISA version (21.4.5) includes the above fix, so I am closing this issue.
