### ISSUE TITLE
something wrong with 35mm.online plugin as well as streaming of TVP Wilno, TVP Historia2 and TVP Kultura2 (TVP_VOD plugin)

### ISSUE THREAD

**Issue by tjtdpwik** [mtr81/kodi_addons#20]
(Kodi21, LibreElec11.95.2)  1 - 35mm.online plugin has not been correctly pointing to movies;  2 - TVP_VOD plugin straming of TVP Wilno, TVP Historia2, TVP Kultura2 is disruppted (chunks of audio are repeated)

**Comment by tjtdpwik** [comment]
Example: FABUŁA->WSZYSTKIE MATERIAŁY - no movies, only documentaries titles I guess (first z Mazurskich Stron)
________________________________

**Comment by mtr81** [comment]
Dlaczego nie piszesz po polsku?

**Comment by tjtdpwik** [comment]
Bo github jest anglojęzyczny 🙂

Od kilku dni obydwie wtyczki 35mm.online (mtr81 i mbebe) nie pokazują tytułów filmów fabularnych. Wszedłem na GitHuba aby to zgłosić zgodnie z tym co przeczytałem, gdy szukałem rozwiązania dlaczego nie działa.

Co to jest ISA, gdzie mam zgłosić problem z TVP Wilno?

Wiem, że na Kodi 20.x jest OK, ale 21 ma dla mnie pewne zalety 🙂
________________________________

**Comment by mtr81** [comment]
InputStream Adaptive - moduł, który odpowiada za odtwarzanie strumieni -> https://github.com/xbmc/inputstream.adaptive . Od razu uprzedzam, że zgłoszenie musi zawierać pełne debuglogi oraz manifesty. Bez tego nawet nie zerkną na zgłoszenie.
ISA została dla potrzeb Kodi 21 przebudowana i nie wszystko działa jak trzeba.
Osobiście mam już dosyć zgłaszania kolejnych problemów, a jak wejdziesz na historię, to ostatnimi czasy robiłem to dosyć często.

**Comment by tjtdpwik** [comment]
Odpuszczę to zgłaszanie 🙁

Dla tych trzech programów znalazłem obejście z wtyczką TVP (Libka) ustawiając catch-up na +5 oraz ręczne wybieranie streamu. Może kiedyś naprawią i z wtyczki TVP_VOD też będzie OK streaming.

A co z 35mm.online, bo ono też nie pokazuje filmów fabularnych na Kodi 20.x?
________________________________

**Comment by mtr81** [comment]
Co do 35mm.online będzie poprawka.

**Comment by mtr81** [comment]
> Odpuszczę to zgłaszanie 🙁 

A ja chyba odpuszczę sobie pisanie wtyczek, bo wychodzi na to że ja mogę poświęcać na to czas i jeszcze za free, a użytkownikom to już za bardzo nic się nie chce ;-)

**Comment by tjtdpwik** [comment]
Szkoda, bo korzystam i podziwiam i dość intensywnie używam  "twórczości" i nie jest to bajer 🙂 Ale mam nadzieję, że 35mm.online jeszcze da się poprawić ? 🙂

A z tym oporem przed zgłaszaniem to nie dlatego, że mi się nie chce. Ja nie jestem programistą a raz zgłaszałem do LibreElec problemy z ProFTPD serwerem (wtyczką) i żeby w ogóle ktoś się pochyli (ostatecznie bardzo skutecznie), to musiałem być instruowany przez kogoś z forum prawie krok po kroku. Wiem, że wtyczka Input Stream Adaptive jest bardzo ważna, bo np korzysta z niej też Netflix plugin i inne tego typu, więc za nim ja się dobiję (jeśli w ogóle) z tymi swoimi problemami z TVP Historia2 czy TVP Wilno do jakiejkolwiek uwagi programistów, to chyba będzie "cud". Kiedyś zgłaszałem coś o niedziałającej wtyczce IPTV Recorder (poprawionej przez Program3r dla Kodi 19+ na LibreElec), to nikt nawet mi nie odpowiedział, a to frustruje. O dziwo ta wtyczka poprawiona przez Program3r działa bez uwag na PC intela. Za głupi jestem aby samemu zdiagnozować dlaczego jest problem z LibreElec (po przejściu na Pythona 3).
________________________________

**Comment by mtr81** [comment]
Poprawka wtyczki 35mm.online poszła do repo, przy czym wersja 1.0.5 jest docelowa (w 1.0,4 zapomniałem o wyszukiwarce, która też generowała niewłaściwą listę). Sprawdź czy jest OK i jak coś daj znać.
Problem z obsługą strumieni live HLS zgłosiłem na GH ISA. Pozostaje czekać co napiszą.

**Comment by tjtdpwik** [comment]
Wielkie dzięki. Sprawdziłem i wszystko jest OK. A tak z ciekawości, co oni zmienili na portalu, że poprzednia wersja wtyczki się "wywalała"? Przypadek czy celowe działanie?

Dzięki za zgłoszenie do GH ISA.  Może ja kiedyś będę "sprawniejszy" w zbieraniu tych logów. Bawię się tym już 5 lat i już od wczoraj jestem na GitHubie - kto wie, co będzie dalej 🙂
________________________________

**Comment by praspp** [comment]
> Poprawka wtyczki 35 mm.online posława do repo, przy czym wersja 1.0.5 jest docelowa (w 1.0,4 zapomniałem o wyszukiwarce, która też generowała niewłasność lista). Sprawdź czy jest OK i jak coś daj znać.

Ja też potwierdzam prawidłowe dzialanie wtyczki w wersji 1.0.5. Dzięki @mtr81 
Czy mógłbyś dodać jeszcze logowanie do konta i synchronizację ulubionych w serwisie?

**Comment by mtr81** [comment]
> A tak z ciekawości, co oni zmienili na portalu, że poprzednia wersja wtyczki się "wywalała"? Przypadek czy celowe działanie?

API, którego używają przewiduje podawanie w jednym z nagłówków zapytania adresu strony www, z którą związane jest to zaputanie. Do tej pory wystarczyło podawać go bez parametrów (np. sposób sortowania wyników), teraz i one są wymagane, mimo że są one już zawarte w url zapytania. Myślę, że to raczej kwestia techniczna niż sposób zabezpieczenia.


> Czy mógłbyś dodać jeszcze logowanie do konta i synchronizację ulubionych w serwisie?

Może kiedyś, przy sprzyjających wiatrach ;-)

**Comment by tjtdpwik** [comment]
Dzięki za info.
________________________________

**Comment by mtr81** [comment]
Jeśli chodzi o telewizję we wtyczce TVP_VOD to umożliwiłem wybór playera - domyślne jest odtwarzanie za pośrednictwem inputstream adaptive (ISA), ale można zmienić je na ffmpeg player (zakładka "Ustawienia" w ustawieniach wtyczki >>> "Typ playera (live, TV)"). Z tego co zauważyłem eliminuje to opisane wyżej problemy z odtwarzaniem. Niestety są i minusy takiego rozwiązania:
- brak możliwości wyboru jakości przed rozpoczęciem odtwarzania (z poprzednich wersji Kodi pamiętam, że nie zawsze odtwarzanie ruszało z najwyższym profilem jakościowym)
- brak bufora czasowego przy korzystaniu z poziomu wtyczki

**Comment by tjtdpwik** [comment]
Na ffmpeg działa bez zarzutu (bez czkawki). Dzięki.
________________________________

**Comment by mtr81** [comment]
Od wersji 1.2.7 zalecane ustawienia wtyczki są następujące:
- Typ playera: **ISA**
- Protokół strumienia: **DASH**

Przy takich ustawieniach nie powinno być problemów z TV (na żywo i archiwum) i transmisjami na żywo z TVP Sport.
Catchup z poziomu IPTV Simple Client jest dostępny przy ustawieniach (Simple Client):
- bufor przed rozpoczęciem programu: **0 minut** (koniecznie !!!)
- kanały obsługują catchup w trybie:  **Wyłączony**

Dodatkowo we wtyczce TVP_VOD nalezy ustawić odpowiednią różnicę czasową. Dla strefy czasowej PL będzie to obecnie **-2 godziny**

**Comment by tjtdpwik** [comment]
Dziękuję!

Działa bardzo dobrze. TVP_VOD skonfigurowałem zgodnie z zaleceniami (ISA,DASH,-2)

Testowałem na TVP_Historia2, TVP_Kultura2 oraz TVP_Wilno (programy, na których obserwowałem problemy wcześniej). TIME_SHIFT oraz CATCH_UP nie używam w Simple Client, więc nie musiałem ich wyłączać 🙂

Z ciekawości, jeśli to nie "tajemnica warsztatowa" - są to workaround'y do błędów ISA, czy streamy TVP są niezgodne ze standardami?
________________________________

**Comment by mtr81** [comment]
ISA od którejś tam wersji dla Kodi 21 nie radzi sobie dobrze z obsługą niektórych strumieni HLS. Zgłosiłem gdzie trzeba, ale prace nad poprawkami idą niemrawo. Stąd decyzja wprowadziłem we wtyczce możliwość wyboru protokołu strumienia. Jeśli chodzi o DASH to ISA radzi sobie dobrze, ale z kolei nie mogę wdrożyć jeszcze jednej rzeczy ze względu na błąd TVP. Przy kanałach na żywo posiadających archiwum powinna być możliwość cofnięcia się z odtwarzaniem do początku bieżącego programu. Niestety dodanie odpowiedniego znacznika czasowego generuje błędny manifest, wskutek czego odtwarzanie zatrzymuje się po kilku sekundach. Sprawdzałem to na różnych wersjach Kodi, ale też na innych odtwarzaczach. W końcu zerknąłem na manifest i rzeczywiście to w nim był problem. Efekt jest taki, że nawet aplikacja HbbTV w Naziemnej TV Cyfrowej nie odtwarza części kanałów...

**Comment by tjtdpwik** [comment]
Dzięki. Jestem pod wrażeniem "głębokości znajomości tematu" 🙂
________________________________
