### ISSUE TITLE
Wtyczka - MAX

### ISSUE THREAD

**Issue by kozak19851** [mtr81/kodi_addons#24]
Hejka... Czy by była możliwość stworzenia wtyczki do platformy - MAX. która od 11.06.2024 jest już dostepna.. Bo przenieśöi z HBO Max i Player wszystko na MAX...

**Comment by zuzia-dev** [comment]
Autor wtyczki HBO MAX pracuje nad MAX: https://forum.kodi.tv/showthread.php?tid=358484&pid=3200941#pid3200941
Choć też uważam, że byłoby świetnie, gdyby wtyczka MAX trafiła do repozytorium @mtr81.

**Comment by mm1992** [comment]
Zdaję sobie sprawę że stworzenie wtyczki wymaga poświęcenia energii i czasu. Jeśli jednak to możłiwe i masz ochotę, to gorąco popieram pomysł stworzenia wtyczki do repozytorium @mtr81. Byłaby lepiej dopasowana do specyfiki polskiego rynku niż amerykańska (chociażby kwestia kanałów telewizyjnych, których jest więcej niż w USA). Dodatkowo, proces tworzenia tamtej wtyczki trwa już rok, i nadal nie został ukończony, stąd nie wiadomo czy tak naprawdę tamta wtyczka powstanie..

**Comment by zuzia-dev** [comment]
Nie trzeba jakoś specjalnie dopasowywać do specyfiki polskiego rynku, bo zasada działania kanałów TV oraz sportu jest taka sama jak w wersji amerykańskiej.  Tyle, że Matt bardzo wysoko zawiesił poprzeczkę i nikt nie śmie przełamać monopolu :)

**Comment by zuzia-dev** [comment]
Kiedyś była rozmowa o tym i Mat uznał, że nie będzie dodawał takiej funkcji dla trzech kanałów jakie były w HBO MAX. A teraz jest inna sytuacja, bo MAX US ma kanał informacyjny. Zresztą jak nie będzie eksportu , można sobie taką listę zrobić samodzielnie. Najważniejsze, aby wtyczka powstała.

**Comment by mtr81** [comment]
Nie pracuję nad wtyczką do tego serwisu i nie mam takich planów.
