### ISSUE TITLE
Wtyczka Megogo

### ISSUE THREAD

**Issue by UncleHoSzczecin** [mtr81/kodi_addons#28]
Problem z wtyczką. Nie pobiera wszystkich kanałów z pakietu. Ani w menu wtyczki ani w pobranej M3U.
Mam pakiet "Max" i brakuje we wtyczce wielu kanałów.

**Comment by mtr81** [comment]
Nie mam aktualnie żadnego pakietu, więc nie jestem w stanie tego sprawdzić.

**Comment by UncleHoSzczecin** [comment]
> Nie mam aktualnie żadnego pakietu, więc nie jestem w stanie tego sprawdzić.

Chcesz to podrzucę Ci login na priv.

**Comment by mtr81** [comment]
A jeszcze pytanie jak się logujesz do tego Megogo? Wtyczka uwzględnia jedynie metodę mail + hasło jako czasowy kod przesłany na e-mail. Z tego względu logowanie należy zacząć od strony megogo.net, wpisując tam e-mail, następnie trzeba odczytać kod przesłany na maila i tymi danymi zalogować się we wtyczce.

**Comment by mtr81** [comment]
Masz na liście we wtyczce coś więcej niż te bezpłatne kanały?

**Comment by UncleHoSzczecin** [comment]
Ok. Nieaktualne. Trzeba było włączyć wsparcie dla DRM domyślnie wyłączone. Może na przyszłość się przydać innym. Dziękuję i przepraszam za problem.

**Comment by UncleHoSzczecin** [comment]
Tak. Część kanałów ponad darmowe było. Teraz po włączeniu wsparcia dla DRM jest już wszystko.

**Comment by mtr81** [comment]
Dokładnie. Takie rozwiązanie zostało jeszcze z czasów kiedy ISA nie radziła sobie z obsługą treści zabezpieczonych DRM z tego serwisu. Odpowiednie zmiany wdrożono dopiero w wersji dla Kodi 21.

**Comment by UncleHoSzczecin** [comment]
Temat zatem zamknięty. Za mało wiedzy miałem. Dzięki!

**Comment by mtr81** [comment]
Obawiam się, że niezależnie od kwestii ustawień wtyczkę trzeba będzie poprawić, bo była ona pisana w momencie, gdy logowanie następowało przy użyciu loginu (adresu e-mail) i hasła. Po jakimś czasie wprowadzili tą weryfikację przy pomocy kodu. Z tego co zauważyłem, że we wtyczce on nie zadziała póki nie użyje się go na megogo.net.

**Comment by UncleHoSzczecin** [comment]
No... Dobra... :D A co mogę zrobić by z wygenerowanej playlisty mi odtwarzało we wtyczce Simply? :D

**Comment by UncleHoSzczecin** [comment]
Od biedy mogę chyba dodać do ulubionych i później sobie z pliku xml przerzucić do m3u ale to takie niekoszerne :D
Zgłaszam zatem problem.

**Comment by mtr81** [comment]
W liście M3U przywoływana jest zła nazwa wtyczki. Ma być: ```plugin://plugin.video.megogo_atv```
Swoją drogą jak po tak długim czasie ktoś to zauważa, to chyba szkoda mojego czasu na pisanie tych wtyczek :-D

**Comment by UncleHoSzczecin** [comment]
Ja muszę korzystać z KODI bo to jedyny sposób na łączenie usług w jednym jednolitym interfejsie. Mam dwoje widzów po 80 roku życia w domu.

**Comment by UncleHoSzczecin** [comment]
Myk z m3u pomógł. W zasadzie dzięki Twojej pomocy mam to czego potrzebowałem ale jeśli faktycznie znajdziesz chwilę dla poprawienia wtyczki to będzie ekstra. Dzięki wielkie!

**Comment by mtr81** [comment]
W wersji 1.0.2 poprawiłem generowanie listy M3U oraz wprowadziłem dodatkową metodę logowania poprzez rejestrację urządzenia w panelu "Moje urządzenia" na megogo.net za pomocą kodu wygenerowanego przez wtyczkę.
