### ISSUE TITLE
[Wtyczka TV Trwam] Drugi kanał Republiki

### ISSUE THREAD

**Issue by mm1992** [mtr81/kodi_addons#29]
W związku z tym że wtyczka nazwana formalnie "TV Trwam" zawiera linki do wielu stacji prawicowych i religijnych,
zgłaszam że TV Republika uruchomiła swój drugi kanał.
Proponuję dodać go do wtyczki.

Prawdopodobnie ma to związek z faktem że posiadają dwie koncesje: jedną naziemną i drugą satelitarną (tą którą mieli wcześniej) i formalnie powinni nadawać różne programy.
Link do drugiego kanału [YT]: /channel/UCZGrD2wCJ7mxgZ2ps2RNKoQ
I transmisja: /watch?v=pMFVsBdcF0E
Nazwa nieformalna (jak widać) to Telewizja Republika Plus. Koncesyjnie jednak, to teraz kanał informacyjny nadaje jako "Republika" (bez przedrostka Telewizja), natomiast ten drugi to "Telewizja Republika" (z przedrostkiem - stara koncesja). Nazwy koncesyjne mogą jednak zmienić w przyszłości, po dokonaniu wniosku do KRRIT.

A tak w ogóle, to mam wrażenie że nazwa i logo tej wtyczki ("TV Trwam") jest nietrafiona właśnie dlatego że tak naprawdę tam można oglądać wiele stacji. Może "Prawicowa TV", albo po prostu podział wtyczek na dwie?

**Comment by mtr81** [comment]
Dzięki za info. Kanał dodałem. Co do nazwy wtyczki, to wynika ona z historii jej powstania. Najpierw plugin obejmował jedynie przekaz live i archiwum TV TRWAM. Pozostałe kanały i stacje radiowe dodałem później.
