### ISSUE TITLE
viaplay pomoc

### ISSUE THREAD

**Issue by rafalmar1981** [mtr81/kodi_addons#30]
Dzień dobry. Przepraszam, że piszę do Ciebie ale nie za bardzo wiem gdzie uderzyć.
Mam problem z wtyczką viaplay, chciałem zobaczyć w nocy mecz MLB pomiędzy Toronto Blue Jays - Baltimore Orioles.
Niestety ciągle pojawiał się komunikat "Nieudane odtwarzanie jednej lub więcej pozycji. Więcej informacji na ten

temat znajdziesz w pliku dziennika diagnostycznego". Sprawdziłem na stronie www, tam mecz leciał.
Kilka informacji zapewne przydatnych:
kodi 20.02 nexus
smart tv android
wtyczka wersja ( 2.3.9 pobrana z Repozytorium-Kodi-1.0.4 - Nexus/zips - plugin.video.viaplay - plugin.video.viaplay-2.3.9.zip
oraz log:
https://paste.kodi.tv/obutopayik
Czy da się to naprawić? Byłbym wdzięczny.
Pozdrawiam.

**Comment by mtr81** [comment]
Dzień Dobry,
Przed chwilą sprawdzałem przekaz live z meczu Yankees-Rangers na wersji, o której piszesz i odtwarzanie przebiegało bez problemów. Podobnie rzecz się ma z transmisjami zakończonymi.

**Comment by rafalmar1981** [comment]
@mtr81  Dziękuję za tak szybką reakcję...fakt kombinowałem później i mi odtwarzało ale częściej zdarzało się jednak ten komunikat i to na innych wydarzeniach sportowych. Poszperałem troszkę:) i znalazłem plugin.video.viaplay-2.4.6_v4 zdaje się, że to od Ciebie magiku i na tej wtyczce bez problemu śmiga wszystko. Tak, że jak coś to dziękuję i mam nadzieję,że nie przysporzyłem kłopotów. Pozdrawiam

**Comment by zuzia-dev** [comment]
> wtyczka wersja ( 2.3.9 pobrana z Repozytorium-Kodi-1.0.4 - Nexus/zips - plugin.video.viaplay - plugin.video.viaplay-2.3.9.zip 

W tym repozytorium jest wersja już nierozwijana choć zasadniczo powinna działać (poza wyszukiwarką). Obecnie najbardziej aktualna wersja jest od @mtr81 i tę polecam instalować: https://github.com/mtr81/plugin.video.viaplay/releases

**Comment by rafalmar1981** [comment]
@zuzia-dev tak podziękował bardzo już ją pobrałem i świetnie działa
