### ISSUE TITLE
aktywuj dźwięk 5.1 (mubi)

### ISSUE THREAD

**Issue by slynobody** [mtr81/kodi_addons#32]
Bardzo, bardzo dziękuję za dodatek Mubi.

czy obsługuje dźwięk 5.1 pochodzący z mubi? 
jeśli nie, jak mogę go aktywować?

**Comment by mtr81** [comment]
Hi,
Thanks!
It is easy to do, but I need to change something in the add-on code. Give me a few days, because I want to implement translation support (based on strings.po file) at the same time...

**Comment by slynobody** [comment]
Thank you! working!
