### ISSUE TITLE
[Player.pl] Brak w pakiecie dla niektórych produkcji

### ISSUE THREAD

**Issue by newkind** [mtr81/kodi_addons#34]
Wczoraj zauważyłem, że niektóre programy wyświetlają informację tym, że nie ma ich w moim pakiecie, pomimo tego, że są.
Wylogowanie się i ponowne zalgowanie naprawia sytuację, ale po kilku godzinach problem wraca. Problem nie występuje we wszystkich programach, a tylko części np.

Fakty - działają bez problemu i konieczności wylogowania/zalogowania
Hotel Paradise (no judging ;)) - trzeba się wylogować i zalogować ponownie

**Comment by mtr81** [comment]
To jest jakieś konto z subskrypcją czy bez?

**Comment by newkind** [comment]
@mtr81 konto z aktywną subskrypcją - plan "Player (bez reklam) 12m"

**Comment by mtr81** [comment]
Był problem z weryfikacją ważności tokena. W wersja 1.0,3, którą wrzuciłem do repo powinno to działać jak należy.

**Comment by newkind** [comment]
Super! Dzięki bardzo za naprawę błędu i wszystkie Twoje wtyczki!
