### ISSUE TITLE
Wybor jakosci streamu we wtyczce Smart TV Go (Vectra)

### ISSUE THREAD

**Issue by isillo** [mtr81/kodi_addons#35]
Od 2-3 tygodni we wtycze do Smart TV Go (Vectra) znacznie pogorszyla sie jakosc obrazu (streamu). Wtyczka nie umozliwia wyboru ktorej rozdzielczosci uzywac i podstawia tylko jedna, pewnie domyslna rozdzielczosc h264, 480x360 co jest bardzo malo. Wczesniej, przed 2 tygodniami standardem byla rozdzielczosc 720. Wiem, ze Vectra nadaje w roznych rozdzielczosciach i jest mozliwy wybor jakosci streamu tak samo jak jest mozliwy wybor sciezki dzwiekowej dla niektorych kanalow. Wybor ten mozliwy jest przz natywna appke ale tez zwyczajnie na stronie WWW. Prosze o zaktualizowanie tej wtyczki do Kodi zeby jakosc byla wyzsza albo byla mozliwosc wyboru strumienia. To wina Vectry bo chyba po prostu zmniejszyli domyslna na 480x360 co jest niewystarczalne.

**Comment by mtr81** [comment]
Zmień ustawienia ISA: "Stream selection type" ustaw na "asq quality". Przed rozpoczęciem odtwarzania pojawi się wówczas okno z możliwością wyboru rozdzielczości.

**Comment by zuzia-dev** [comment]
We wtyczce jest pełna jakość, aż do 4K.  @isillo zmień ustawienia na podane wyżej.

**Comment by mtr81** [comment]
ISA- plugin InputStream Adaptive, który steruje odtwarzaniem w tej wtyczce. Wejdź do jego ustawień (Add-ons-> My Add-ons -> VideoPlayer InputStream -> InputStream Adaptive -> settings) i w nich "Stream selection type" ustaw na "Ask quality" albo "Manual OSD"
