### ISSUE TITLE
viaplay

### ISSUE THREAD

**Issue by rafalmar1981** [mtr81/kodi_addons#37]
która wersja wtyczki  jest dobra bo kombinowałem z różnymi i . Pozdrawiam

**Comment by mm1992** [comment]
Kto by się tym przejmował, i tak wychodzą z polskiego rynku. Sam nie wiem która jest najlepsza, wtyczki były strasznie rozdrobnione i rozwijane przez różne grupy.

**Comment by rafalmar1981** [comment]
Ale @mtr81 na pewno będzie wiedział co i jak,
Próby robiłem na 2.4.6_v1   2.4.6_v2   2.4.6_v3  

2.4.6_v1 logowanie poprawne, wejście  np. w kategorię film jest oki ale w kolejną podkategorię już nie wchodzi, kanały TV nieudane odtwarzanie
Podam log:
https://paste.kodi.tv/beyuhicaru

2.4.6_v2 logowanie poprawne, wejście  np. w kategorię film jest oki ale w kolejną podkategorię już nie wchodzi, kanały TV nieudane odtwarzanie
Podam log:
https://paste.kodi.tv/dupiqelufe

2.4.6_v3 logowanie poprawne, wejście  np. w kategorię film jest oki ale w kolejną podkategorię już nie wchodzi, kanały TV nieudane odtwarzanie logi już nie podaję bo tak samo
Za każdym razem odinstalowywałem i czyściłem tv
To już koniec? czy coś jeszcze będzie naprawione? Pytanie do  @mtr81 . Pozdrawiam

**Comment by Cinek77** [comment]
Najlepiej to problemy zgłaszać u autora wtyczki w odpowiednim miejscu, a nie gdzie popadnie.

**Comment by mtr81** [comment]
Nic dodać, nic ująć. W związku z powyższym wątek zamykam.
