### ISSUE TITLE
Witam

### ISSUE THREAD

**Issue by rafalmar1981** [mtr81/kodi_addons#38]
Cos z tym viapplay da się. Zrobić poprzednnia wiaadomosc znniknele

**Comment by mtr81** [comment]
Witam
Zamykam te wątki, bo uporczywie zgłaszasz problem nie tam gdzie trzeba. Rób to [tutaj](https://github.com/Mariusz89B/plugin.video.viaplay/issues) ewentualnie na [forku](https://github.com/mtr81/plugin.video.viaplay/issues), gdzie przeniosłem jedno ze zgłoszeń. W tym ostatnim miejscu jest też wersja, która powinna działać (do instalacji ręcznej) - https://github.com/mtr81/plugin.video.viaplay/releases/download/v2.4.6_v5/plugin.video.viaplay-2.4.6_v5.zip
