### ISSUE TITLE
[plugin.video.player_pl / plugin.video.vod_pl] Kanały TVP nie działają.

### ISSUE THREAD

**Issue by mm1992** [mtr81/kodi_addons#39]
Serwis player.pl dołączył do swojej oferty kanały TVP. Wyświetlają się one na liście w obu wymienionych wtyczkach, ale nie działają.
W serwisie w wersji przeglądarkowej wymienione kanały są dostępne bez konieczności opłacenia pakietu, więc można łatwo testować.

P.S. Dodajmy że wtyczka VOD.pl mimo że serwis zniknął, nadal działa, i to bez logowania, dlatego nie ma co jej zamykać.

Fragment z logu:
`ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'KeyError'>
Error Contents: 'protections'
Traceback (most recent call last):
File "{wycięte}\addons\plugin.video.player_pl\addon.py", line 1187, in <module>
playVid(cid,'live',False,True,ts,te,pid)
File "{wycięte}\addons\plugin.video.player_pl\addon.py", line 460, in playVid
if 'widevine' in resp['movie']['video']['protections']:
KeyError: 'protections'
-->End of Python script error report<--`

**Comment by mtr81** [comment]
Dzięki. Dostosowałem wtyczki do kanałów TVP i wrzuciłem do repo.
