### ISSUE TITLE
[TVP_VOD] problem z odtwarzaniem materiałów z archiwum TV

### ISSUE THREAD

**Issue by Slawomir1959** [mtr81/kodi_addons#42]
witam, tvp_vod : jesli wybieram ,np. kanal kultura , fim nadany kilka dni temu/ system przechowuje wszystko tydzien, co widze w systemie, czy tez moge to zminic na dluzej?/ , to system nie odtwarza tego filmu, ten problem dotyczy wszystkiego,co jest podane na dany tydzien. dziala : na zywo lub np.serial .  ten problem jest na kazdym urzadzeniu, np, windows czy android...wczesniej  nie bylo tego problemu.prosze o informacje, pomoc, serd.dziekuje za te wtyczke...pozdrawiam ...

**Comment by mtr81** [comment]
Witam
Po przełączeniu w ustawieniach wtyczki **typu strumienia** na "**HLS**" programy z archiwum powinny się odtwarzać prawidłowo.  Strumieniowanie oparte na protokole DASH od kilku dni działa jedynie w odniesieniu do przekazu live. Problem leży po stronie dostawcy usługi (TVP), co można to zweryfikować w wersji przeglądarkowej serwisu (https://vod.tvp.pl).
Co do zmiany długości okresu archiwum, to nie ma takiej możliwości.
Pozdrawiam

**Comment by Slawomir1959** [comment]
witam , na wszystkich urządzeniach ta wtyczka miała protokół strumienia: dash, i co ciekawe: wcześniej wszystko z archiwum było odtwarzane. zmieniłem teraz na hls i działa dobrze. serd. dziękuje za te informacje-pomoc. sam bym na to nie wpadł, aby zmienić typ  strumienia. teraz jest tak : dash- na żywo -ok, archiwum- nie; hls na żywo i archiwum- ok.  serd.pozdrawiam

**Comment by mtr81** [comment]
Z tego co widzę TVP uporała się z problemem - programy z archiwum otwierają się niezależnie od rodzaju protokołu strumienia (DASH/HLS). Jest tak na vod.tvp.pl jak i we wtyczce.
W związku z powyższym wątek zamykam.
