### ISSUE TITLE
[EUROVISION SPORT] Odtwarzanie archiwalne (VOD) nie jest możliwe

### ISSUE THREAD

**Issue by werimail** [mtr81/kodi_addons#43]
Witaj @mtr81, w dodatku Kodi „Eurovision Sport” nie można już odtwarzać treści archiwalnych (VOD) pomimo udanej rejestracji na stronie https://eurovisionsport.com/, pojawia się komunikat o błędzie. Testowałem go pod Kodi Omega (21.1) w dziale „Biathlon”. 

W załączeniu plik [kodi.log](https://github.com/user-attachments/files/17993031/kodi.log)

Pozdrawiam werimail

**Comment by mtr81** [comment]
Hi,
Thank you for information! Try this version:
[plugin.video.eurovisionsport-1.0.2.zip](https://github.com/user-attachments/files/17996730/plugin.video.eurovisionsport-1.0.2.zip)
It works on Kodi 21 (tested on WIN 10 64bit), but there's some problem in Kodi 22 (I get 404 error after license requests)

**Comment by mtr81** [comment]
I got it! This version should be work also on Kodi 22 
[plugin.video.eurovisionsport-1.0.2.zip](https://github.com/user-attachments/files/17997255/plugin.video.eurovisionsport-1.0.2.zip)

**Comment by werimail** [comment]
Thanks @mtr81, with the latest version the VOD streams are working again for me (on Kodi 21.1 with WIN 11 64bit) . This means that it can also be published in your official repository.

Thanks and regards werimail
