### ISSUE TITLE
TVP.VOD: TV GO+ 

### ISSUE THREAD

**Issue by Huero23** [mtr81/kodi_addons#45]
![20241210_195052](https://github.com/user-attachments/assets/ba41b654-813f-42e1-81bc-b6b271795115)
Nie wchodzi loading Panorma, Jeden Z Dziesięciu , żadne seriale tvp 2 albo tvp 1. Czy można poprosić o poprawkę.

**Comment by mtr81** [comment]
Tak, problem znam - dotyczy zakładki Inne serwisy TVP >>> TVP GO+ >>> Replay TV(new). Poprawka jest gotowa, ale pojawi się w repo razem z pakietem poprawek/zmian do innych wtyczek. Tymczasem z archiwum TV można również korzystać poprzez zakładki:

- Inne serwisy TVP >>> TVP GO+ >>> Replay TV
- Archiwum TV (test)
