### ISSUE TITLE
Lista kanałów

### ISSUE THREAD

**Issue by 777martin777** [mtr81/kodi_addons#6]
Dzień dobry!
Na wstępie, dzięki za świetne pluginy. Bardzo przydatne. I pytanie: czy da się wyświetlić listę kanałów na OSD (bez wychodzenia z odtwarzania) w takich pluginach jak TVP czy MEGOGO?
Pozdrawiam
Marcin

**Comment by mtr81** [comment]
Dzień Dobry
W tych jaki i innych moich wtyczkach nie ma takiej możliwości. Dostęp do poprzedniego menu (w przypadku live TV - do listy kanałów) jest możliwy bez przerywania odtwarzania w inny sposób - przykładowo w wersji na Windows poprzez użycie klawisza Esc.
Pozdrawiam

**Comment by 777martin777** [comment]
Ok, dziękuje za odpowiedź.
