### ISSUE TITLE
Reaktywacja wtyczki Open FM

### ISSUE THREAD

**Issue by aprof28** [mtr81/kodi_addons#8]
Witam.  https://github.com/pajretX/plugin.audio.open_FM czy można ją reaktywować . Byłoby super.

**Comment by mtr81** [comment]
Witam
Wtyczka do Open FM jest w repo innego developera https://github.com/Lantash77/lantash-repo/tree/main

**Comment by aprof28** [comment]
Dziękuję. Znalazłem. Pozdrawiam.
